import type { Metadata } from "next";
import Aside from "@/componentes/layout/Aside";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen w-full">
      <Aside />
      <main className="w-full">{children}</main>
    </div>
  );
}
